name: "generate release"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  tagged-release:
    name: "Generate release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: Step 1 - Checkout main branch from Github
        uses: actions/checkout@main
      - name: Step 2 - Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Step 3 - Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Step 4 - Generate the artifacts
        uses: skx/github-action-build@master
        with:
          builder: .github/build
      - name: Step 5 - Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'target/statique.zip'
      
